mash/mash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from mash.mashapp.api_views import CategoryViewSet, PostViewSet
import rest_framework
router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'posts', PostViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mashapp.urls')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path('category-detail/', include(router.urls)), path('api/v0/', include(router.urls)), # Поправил путь для категорий
]

mash/mashapp/urls.py
from django.urls import path
from . import views
from .models import Project

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('projects/', views.projects, name='projects'),
    path('resume/', views.resume, name='resume'),
    path('', views.project_list, name='project_list'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('submit-contact-form/', views.submit_contact_form, name='submit_contact_form'),
    path('create/', views.create, name='create'),
    path('create/<int:post_id>/', views.view_post, name='view_post'),
    path('resume/', views.resume_view, name='resume'),
    path('tag-list/', views.TagListView.as_view(), name='tag_list'),
    path('tag-detail/<int:pk>/', views.TagDetailView.as_view(), name='tag_detail'),
    path('tag-create/', views.TagCreateView.as_view(), name='tag_create'),
    path('tag-update/<int:pk>/', views.TagUpdateView.as_view(), name='tag_update'),
    path('tag-delete/<int:pk>/', views.TagDeleteView.as_view(), name='tag_delete'),
    path('contactform/', views.contact_view, name='contactform'),
    path('category-detail/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('post-category-create/<int:pk>', views.PostCategoryCreateView.as_view(), name='post-category-create')

    ]

mash/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView

app_name = 'usersapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register')

]

mash/mashapp/models.py
from django.db import models
from django.conf import settings
from usersapp.models import BlogUser
from rest_framework import routers, serializers, viewsets
from django.contrib import admin
from django.urls import path, include

class AcriveManager(models.Manager):
    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)
class IsActiveMixin(models.Model):
    is_active = models.BooleanField(default=False)
    objects = models.Manager()
    active_objects = AcriveManager()
    class Meta:
        abstract = True

# class UpdatedObjectsManager(models.Manager):
#     def get_queryset(self):
#         all_objects = super().get_queryset()
#         return all_objects.filter(is_active=True)

class TimeStamp (models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='project_images/', null=True, blank=True)
    # Другие поля, которые вам нужны
    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Tag(IsActiveMixin):
    objects = models.Manager()
    active_objects = AcriveManager()
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    @property
    def text(self):
        return self.name

from django.db import models
from django.urls import reverse

class Page(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)


    def get_absolute_url(self):
        return reverse('view_post', args=[str(self.id)])

    page = models.ForeignKey(Page, on_delete=models.CASCADE, null=True, blank=True)



class CoreObject(models.Model):
    name = models.CharField(max_length=32)

class Cer(CoreObject):
    description = models.TextField()

class Toy(CoreObject):
    text = models.TextField()


class Create(models.Model):
    objects = models.Manager()
    active_objects = AcriveManager()
    name = models.CharField(max_length=32, unique=True)
    text = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_posts')
    tags = models.ManyToManyField(Tag)
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(default=1)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def has_image(self):
        return bool(self.image)

    def some_method(self):
        return "hello world"

mash/mashapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Tag
from .models import Category
from django import forms
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django import forms
from .models import Create, Page
from django import forms
from .models import Tag  # Импортируйте Tag из models

class MashForm(forms.ModelForm):
    # name_icontains = forms.CharField(widget=forms.TextInput(attrs={''}))
    name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))
    text = forms.CharField(label='Description', widget=forms.Textarea())
    page = forms.ModelChoiceField(queryset=Page.objects.all(), label='Страница')

    class Meta:
        model = Create
        exclude = []  # Убираем 'user' из исключенных полей


class ContactForm(forms.Form):
    name = forms.CharField(label='Название')
    email = forms.EmailField(label='email')
    message = forms.CharField(label='Сообщение')

class PostCategoryForm(forms.ModelForm):
    name = forms.CharField(label='Название', widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Create
        fields = ['name', 'text', 'tags', 'image', 'rating']  # Включаем все поля, кроме 'user' и 'category'

mash/mashapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.base import ContextMixin
from .models import Project, Category
from django.template.loader import get_template
from django.http import HttpResponse, HttpResponseRedirect
import json
from django.core.validators import EmailValidator, RegexValidator, URLValidator, ValidationError
from django.http import JsonResponse
from django.http import Http404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    posts = Create.active_objects.all()
    paginator = Paginator(posts, 1)  # Показывать по 2 поста на странице
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    title = 'Главная страница'
    return render(request, 'mashapp/index.html', {'posts': posts, 'title': title})


def contact(request):
    title = "Контакты"
    return render(request, 'mashapp/contact.html', context={'title': title})


@user_passes_test(lambda u: u.is_superuser)
def projects(request):
    return render(request, 'mashapp/projects.html')

def resume(request):
    title = "Информация"
    return render(request, 'mashapp/resume.html', context={'title': title})

def project_list(request):
    title = "Проекты"
    projects = Project.objects.all()
    return render(request, 'project_list.html', {'projects': projects, 'title': title})

def project_detail(request, project_id):
    project = Project.objects.get(id=project_id)
    template = get_template('project_detail.html')
    html = template.render({'project': project})
    return HttpResponse(html)

required_fields = ['name', 'email', 'phone']

def is_valid_email(email):
    try:
        EmailValidator(email)
        return True
    except ValidationError:
        return False

def is_valid_phone(phone):
    if phone[0] != '+':
        return False, "Phone number must start with '+'"
    if len(phone) != 12:
        return False, "Phone number must be 12 characters long"
    for char in phone[1:]:
        if not char.isdigit():
            return False, "Phone number must contain only digits after the country code"
    return True, None

def submit_contact_form(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        phone = request.POST.get('phone', '')

        is_valid, error_message = is_valid_phone(phone)
        if not is_valid:
            return JsonResponse({'success': False, 'error': error_message}, status=400)

        if not is_valid_email(email):
            return JsonResponse({'success': False, 'error': 'Invalid email address'}, status=400)

        data = {
            'name': name,
            'email': email,
            'phone': phone,
            'message': message
        }
        try:
            with open('contact_data.json', 'w') as f:
                json.dump(data, f)
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=500)

        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'error': 'Method not allowed'}, status=405)

from .models import Page, Post

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Tag, Create
from .forms import MashForm, PostCategoryForm


@login_required
def create(request):
    if request.method == 'POST':
        form = MashForm(request.POST)
        if form.is_valid():
            create_instance = form.save(commit=False)
            create_instance.user = request.user  # Устанавливаем текущего пользователя
            create_instance.save()

            # Получаем страницу из формы и создаем новый объект Post, связанный с этой страницей и пользователем
            page = form.cleaned_data['page']
            post = Post.objects.create(page=page, title=create_instance.name, content=create_instance.text, user=request.user)  # Устанавливаем текущего пользователя
            post_url = post.get_absolute_url()

            return redirect('view_post', post_id=post.id)
    else:
        form = MashForm()
    return render(request, 'mashapp/create.html', {'form': form})

class NameContextMixin(ContextMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = 'Список тэгов'
        return context

def view_post(request, post_id):
    try:
        post = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        raise Http404("Пост не найден")
    return render(request, 'mashapp/post_detail.html', {'post': post})

def resume_view(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'resume.html', context)

class TagListView(ListView, NameContextMixin):
    model = Tag
    template_name = 'tag_list.html'
    context_object_name = 'tags'
    paginate_by = 1

    def get_queryset(self):
        return Tag.active_objects.all()

class TagDetailView(UserPassesTestMixin, DetailView, NameContextMixin):
    model = Tag
    template_name = 'mashapp/tag_detail.html'
    def test_func(self):
        return self.request.user.is_superuser

    context_object_name = 'tags'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = 'Список тэгов'
        return context

class TagCreateView(LoginRequiredMixin, CreateView, NameContextMixin):
    fields = '__all__'
    model = Tag
    success_url = reverse_lazy('tag_list')
    template_name = 'mashapp/tag_create.html'

    def form_valid(self, form):
        return super().form_valid(form)

class TagUpdateView(UserPassesTestMixin, UpdateView, NameContextMixin):
    fields = '__all__'
    model = Tag
    success_url = reverse_lazy('tag_list')
    template_name = 'mashapp/tag_create.html'
    def test_func(self):
        return self.request.user.is_superuser

class TagDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'mashapp/tag_delete_confirm.html'
    model = Tag
    success_url = reverse_lazy('tag_list')
    def test_func(self):
        return self.request.user.is_superuser


from .forms import ContactForm



def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Здесь вы можете обработать валидные данные формы
            # Например, отправить email или сохранить данные в базу данных
            return HttpResponseRedirect('/resume/')  # Перенаправление после успешной обработки
    else:
        form = ContactForm()
    return render(request, 'mashapp/contactform.html', {'form': form})

class CategoryDetailView(DetailView):
    template_name = 'mashapp/category_detail.html'
    model = Category
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['form'] = PostCategoryForm()
        return context
from django.shortcuts import get_object_or_404
from django.urls import reverse

class PostCategoryCreateView(CreateView):
    model = Create
    template_name = 'category_detail.html'
    success_url = '/'
    form_class = PostCategoryForm

    def post(self, request, *args, **kwargs):
        self.category_pk = kwargs['pk']
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        category = get_object_or_404(Category, pk=self.category_pk)
        form.instance.category = category
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('category_detail', kwargs={'pk': self.category_pk})

mash/mashapp/templates/base.html
{% load static %} <!-- Добавляем загрузку статических файлов -->
{% load str_extensions %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}Personal - Start Bootstrap Theme{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Custom Google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'index' %}"><span class="fw-bolder text-primary">{{title|nexta}}</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                        <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'resume' %}">Resume</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'projects' %}">Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'create' %}">Create</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'tag_list' %}">Список тегов</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contactform' %}">Формы</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">Привет, {{ user.username }}<a class="nav-link" href="{% url 'users:logout' %}"> Выход</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Вход</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End of Navigation-->

        <!-- Content block -->
        {% block content %}
        {% endblock %}
        <!-- End of Content block -->
    </main>
</body>
</html>

<!-- template.html -->

{% for post in page.post_set.all %}
    <h2>{{ post.title }}</h2>
    <p>{{ post.content }}</p>
    {% if post.image %} <!-- Проверяем наличие изображения -->
        <img src="{{ post.image.url }}" alt="{{ post.title }}"> <!-- Отображаем изображение -->
    {% endif %}
{% endfor %}

       <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">{{joke}}</div></div>
                    <div class="col-auto">
                        <a class="small" href="{% url 'resume' %}">Privacy</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="{% url 'create' %}">Terms</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="{% url 'contact' %}">Contact</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

mash/mashapp/templates/project_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h2>{{ project.title }}</h2>
  <p>{{ project.description }}</p>
  <img src="{{ project.image.url }}" alt="{{ project.title }}">
{% endblock %}

mash/mashapp/templates/project_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% for project in projects %}
    <h2><a href="{% url 'project_detail' project.pk %}">{{ project.title }}</a></h2>
    <p>{{ project.description }}</p>
  {% endfor %}
{% endblock %}